name: "Build"

on:
  pull_request:
  push:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        # TODO: sanitize: [On, Off]
        os: [ubuntu-24.04]
        # TODO: Enable release once we no longer have a Clang crash:
        # https://github.com/jank-lang/jank/actions/runs/12269972895/job/34234432107
        build_type: [Debug]
        include:
          - os: ubuntu-24.04
            cc: clang-14
            cxx: clang++-14
          - os: ubuntu-24.04
            build_type: Debug
            codecov: on
            analysis: on
    runs-on: ${{ matrix.os }}
    env:
      CC: ${{ matrix.cc }}
      CXX: ${{ matrix.cxx }}
      CODECOV: ${{ matrix.codecov }}
      ANALYSIS: ${{ matrix.analysis }}
    timeout-minutes: 240 # 4h
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build and test
        uses: ./.github/actions/build
        id: build
        with:
          update_release: ${{ github.ref == 'refs/heads/main' && matrix.build_type == 'Release' }}
      - name: Update latest release
        if: success() && github.ref == 'refs/heads/main' && ${{ matrix.build_type == 'Release' }}
        uses: pyTooling/Actions/releaser@main
        with:
          tag: latest
          rm: true
          token: ${{ secrets.GITHUB_TOKEN }}
          files: ${{ steps.build.outputs.release_archive }}
